import React, { useEffect, useRef, useState } from 'react';
import { analyzeIncidentImage, type IncidentAnalysisResult } from '../utils/imageScanEngine';

export interface IncidentScanResult extends IncidentAnalysisResult {
  imageDataUrl?: string;
}

export interface ScanCompleteResultData {
  transcript: string;
  coordinates: [number, number];
  category: string;
  verificationScore: number;
}

interface ImageScanModalProps {
  isOpen: boolean;
  onClose: () => void;
  selectedCoordinates: [number, number];
  onAnalysisComplete?: (result: IncidentScanResult) => void;
  onScanComplete?: (resultData: ScanCompleteResultData) => void;
}

const defaultLabels = ['cracked asphalt', 'traffic obstruction', 'debris'];

export default function ImageScanModal({
  isOpen,
  onClose,
  selectedCoordinates,
  onAnalysisComplete,
  onScanComplete
}: ImageScanModalProps) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const streamRef = useRef<MediaStream | null>(null);

  const [mode, setMode] = useState<'upload' | 'camera'>('upload');
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [isScanning, setIsScanning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isCameraActive, setIsCameraActive] = useState(false);
  const [detectedLabels, setDetectedLabels] = useState<string[]>(defaultLabels);

  useEffect(() => {
    if (!isOpen) {
      stopCamera();
      setIsCameraActive(false);
      return;
    }

    if (mode === 'camera') {
      startCamera();
    }

    return () => {
      stopCamera();
    };
  }, [isOpen, mode]);

  const stopCamera = () => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((track) => track.stop());
      streamRef.current = null;
    }
    setIsCameraActive(false);
  };

  const startCamera = async () => {
    try {
      setError(null);
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment' },
        audio: false
      });

      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }
      setIsCameraActive(true);
    } catch (cameraError) {
      setError('Unable to access the camera. Please upload an image instead.');
      setIsCameraActive(false);
    }
  };

  const handleImageProcess = async (imageDataUrl: string) => {
    const cleanBase64 = imageDataUrl.includes('base64,')
      ? imageDataUrl.split('base64,')[1]
      : imageDataUrl;

    setSelectedImage(imageDataUrl);
    setIsScanning(true);
    setError(null);

    try {
      const result = await analyzeIncidentImage(cleanBase64);

      const labels = result.detectedObjects.length
        ? result.detectedObjects
        : defaultLabels;

      setDetectedLabels(labels);

      const payload: IncidentScanResult = {
        ...result,
        imageDataUrl
      };

      const scanData: ScanCompleteResultData = {
        transcript: result.autoGeneratedTranscript,
        coordinates: selectedCoordinates,
        category: result.detectedCategory,
        verificationScore: Number(Math.min(0.99, Math.max(0.1, result.confidenceScore || 0.8)).toFixed(2))
      };

      onAnalysisComplete?.(payload);
      onScanComplete?.(scanData);
    } catch (analysisError) {
      const message =
        analysisError instanceof Error
          ? analysisError.message
          : 'Unable to analyze the image. Please try another photo.';

      setError(message);
    } finally {
      setIsScanning(false);
    }
  };

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async () => {
      const result = typeof reader.result === 'string' ? reader.result : '';
      if (result) {
        await handleImageProcess(result);
      }
    };
    reader.readAsDataURL(file);
  };

  const handleCaptureFromCamera = async () => {
    if (!videoRef.current) return;

    const canvas = document.createElement('canvas');
    const context = canvas.getContext('2d');
    const video = videoRef.current;

    canvas.width = video.videoWidth || 1280;
    canvas.height = video.videoHeight || 720;

    if (!context) {
      setError('Camera capture is not supported on this device.');
      return;
    }

    context.drawImage(video, 0, 0, canvas.width, canvas.height);
    const dataUrl = canvas.toDataURL('image/jpeg');
    await handleImageProcess(dataUrl);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4 backdrop-blur-sm">
      <div className="w-full max-w-4xl overflow-hidden rounded-2xl border border-slate-700 bg-slate-900 shadow-2xl shadow-slate-950/70">
        <div className="flex items-center justify-between border-b border-slate-700 bg-slate-900 px-5 py-4">
          <div>
            <p className="text-xs uppercase tracking-[0.2em] text-cyan-400">Image Scan</p>
            <h3 className="text-xl font-semibold text-white">Incident Analysis</h3>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="rounded-md border border-slate-600 px-3 py-1.5 text-sm text-slate-200 transition hover:bg-slate-800"
          >
            Close
          </button>
        </div>

        <div className="grid gap-6 p-5 lg:grid-cols-[1.1fr_0.9fr]">
          <div className="space-y-4">
            <div className="flex gap-2 rounded-xl border border-slate-700 bg-slate-950 p-1">
              <button
                type="button"
                onClick={() => setMode('upload')}
                className={`flex-1 rounded-lg px-3 py-2 text-sm font-medium transition ${
                  mode === 'upload' ? 'bg-cyan-500 text-slate-950' : 'text-slate-300 hover:bg-slate-800'
                }`}
              >
                Upload Image
              </button>
              <button
                type="button"
                onClick={() => setMode('camera')}
                className={`flex-1 rounded-lg px-3 py-2 text-sm font-medium transition ${
                  mode === 'camera' ? 'bg-cyan-500 text-slate-950' : 'text-slate-300 hover:bg-slate-800'
                }`}
              >
                Use Camera
              </button>
            </div>

            {mode === 'upload' && (
              <div className="rounded-2xl border border-dashed border-slate-600 bg-slate-950/70 p-4 text-center">
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  onChange={handleFileUpload}
                  className="hidden"
                />

                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  className="inline-flex items-center justify-center rounded-xl bg-cyan-500 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-cyan-400"
                >
                  Select Incident Photo
                </button>
              </div>
            )}

            {mode === 'camera' && (
              <div className="space-y-3">
                <div className="relative overflow-hidden rounded-2xl border border-slate-700 bg-slate-950">
                  <video
                    ref={videoRef}
                    autoPlay
                    playsInline
                    muted
                    className={`h-[280px] w-full object-cover ${isCameraActive ? 'block' : 'hidden'}`}
                  />

                  {!isCameraActive && (
                    <div className="flex h-[280px] items-center justify-center rounded-2xl bg-slate-950 text-sm text-slate-400">
                      Camera is starting...
                    </div>
                  )}
                </div>

                <button
                  type="button"
                  onClick={handleCaptureFromCamera}
                  className="inline-flex w-full items-center justify-center rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400"
                >
                  Capture Photo
                </button>
              </div>
            )}

            {isScanning && (
              <div className="rounded-2xl border border-cyan-500/40 bg-slate-950 p-4">
                <div className="mb-2 flex items-center gap-2 text-sm text-cyan-300">
                  <span className="h-2.5 w-2.5 animate-pulse rounded-full bg-cyan-400" />
                  Analyzing infrastructure damage using AI Vision...
                </div>

                <div className="relative h-2 overflow-hidden rounded-full bg-slate-800">
                  <div className="scanner-beam absolute inset-y-0 left-0 w-1/3 bg-gradient-to-r from-transparent via-cyan-400 to-transparent animate-[scan_1.8s_ease-in-out_infinite]" />
                </div>
              </div>
            )}

            {error && (
              <div className="rounded-xl border border-red-500/40 bg-red-500/10 p-3 text-sm text-red-200">
                {error}
              </div>
            )}
          </div>

          <div className="rounded-2xl border border-slate-700 bg-slate-950 p-3">
            <div className="mb-3 flex items-center justify-between">
              <p className="text-sm font-medium text-slate-200">Photo Preview</p>
              {selectedImage && (
                <span className="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-1 text-[10px] uppercase tracking-[0.2em] text-emerald-300">
                  Ready
                </span>
              )}
            </div>

            <div className="relative overflow-hidden rounded-xl border border-slate-700 bg-slate-900">
              {selectedImage ? (
                <>
                  <img src={selectedImage} alt="Incident preview" className="h-[320px] w-full object-cover" />

                  <div className="pointer-events-none absolute inset-0">
                    {detectedLabels.map((label, index) => {
                      const positions = [
                        { left: '12%', top: '18%' },
                        { left: '52%', top: '25%' },
                        { left: '36%', top: '62%' },
                        { left: '68%', top: '48%' }
                      ];

                      const position = positions[index % positions.length];

                      return (
                        <div
                          key={`${label}-${index}`}
                          className="absolute rounded-full border border-cyan-400/80 bg-slate-900/80 px-2 py-1 text-[10px] font-medium text-cyan-300 shadow-lg shadow-cyan-900/40"
                          style={{
                            left: position.left,
                            top: position.top,
                            transform: 'translate(-50%, -50%)'
                          }}
                        >
                          {label}
                        </div>
                      );
                    })}
                  </div>
                </>
              ) : (
                <div className="flex h-[320px] items-center justify-center text-sm text-slate-500">
                  No image captured yet
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
