/**
 * Vision-based incident analysis utility for civic infrastructure images.
 * This module prepares a base64-encoded image and sends it to a Vision-capable LLM API.
 * It expects a JSON response with civic issue classification details.
 */

export type IncidentSeverity = 'High' | 'Medium' | 'Low';

export interface IncidentAnalysisResult {
  detectedCategory: string;
  severity: IncidentSeverity;
  autoGeneratedTranscript: string;
  detectedObjects: string[];
  confidenceScore: number;
}

export interface VisionApiResponse {
  choices?: Array<{
    message?: {
      content?: string;
    };
  }>;
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
  }>;
  error?: {
    message?: string;
  };
}

const CIVIC_PROMPT = `
You are a civic infrastructure assistant. Analyze the provided incident image and determine whether it shows a civic infrastructure issue.

Return valid JSON only with the following structure:
{
  "detectedCategory": "Road Infrastructure | Water Supply | Electricity | Disaster Management | Waste Management | Public Safety",
  "severity": "High | Medium | Low",
  "autoGeneratedTranscript": "A detailed 2-sentence citizen-style description of the incident.",
  "detectedObjects": ["object 1", "object 2"],
  "confidenceScore": 0.94
}

Examples of relevant civic issues include: bridge damage, road collapse, flooding, garbage pile, water pipe leak, fallen electric line, blocked drainage, broken sidewalk, or traffic accident.

If the image is not a civic issue, unreadable, blurry, or unrelated to public infrastructure, return:
{
  "detectedCategory": "Unclear",
  "severity": "Low",
  "autoGeneratedTranscript": "The uploaded image does not clearly show a relevant civic infrastructure issue or appears unreadable.",
  "detectedObjects": [],
  "confidenceScore": 0.12
}
`;

function isValidIncidentAnalysis(result: Partial<IncidentAnalysisResult>): boolean {
  return Boolean(
    result.detectedCategory &&
    result.severity &&
    result.autoGeneratedTranscript &&
    Array.isArray(result.detectedObjects) &&
    typeof result.confidenceScore === 'number'
  );
}

function parseJsonResponse(rawText: string): IncidentAnalysisResult {
  const cleaned = rawText
    .replace(/```json\s*/gi, '')
    .replace(/```\s*$/g, '')
    .trim();

  const parsed = JSON.parse(cleaned);

  return {
    detectedCategory: String(parsed.detectedCategory || 'Unclear'),
    severity: (parsed.severity === 'High' || parsed.severity === 'Medium' || parsed.severity === 'Low')
      ? parsed.severity
      : 'Low',
    autoGeneratedTranscript: String(
      parsed.autoGeneratedTranscript ||
      'The uploaded image does not clearly show a relevant civic infrastructure issue or appears unreadable.'
    ),
    detectedObjects: Array.isArray(parsed.detectedObjects) ? parsed.detectedObjects.map(String) : [],
    confidenceScore: Number(parsed.confidenceScore ?? 0.12)
  };
}

/**
 * Analyze an uploaded incident image using a Vision-capable LLM API.
 * The function accepts a base64-encoded image and calls the configured model endpoint.
 */
export async function analyzeIncidentImage(base64Image: string): Promise<IncidentAnalysisResult> {
  if (!base64Image || typeof base64Image !== 'string') {
    throw new Error('A valid base64 image payload is required.');
  }

  const apiKey = process.env.VISION_LLM_API_KEY;
  const apiUrl = process.env.VISION_LLM_API_URL || 'https://api.openai.com/v1/chat/completions';

  if (!apiKey) {
    throw new Error('VISION_LLM_API_KEY is not configured.');
  }

  try {
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'user',
            content: [
              { type: 'text', text: CIVIC_PROMPT },
              {
                type: 'image_url',
                image_url: {
                  url: `data:image/jpeg;base64,${base64Image}`
                }
              }
            ]
          }
        ],
        temperature: 0.2,
        response_format: { type: 'json_object' }
      })
    });

    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`AI vision request failed: ${response.status} ${errorBody}`);
    }

    const result: VisionApiResponse = await response.json();
    const content =
      result.choices?.[0]?.message?.content ||
      result.candidates?.[0]?.content?.parts?.map((part) => part.text || '').join('') ||
      '';

    if (!content) {
      throw new Error('AI vision response was empty.');
    }

    const parsedResult = parseJsonResponse(content);

    if (!isValidIncidentAnalysis(parsedResult)) {
      throw new Error('AI model returned an invalid civic-analysis response.');
    }

    return parsedResult;
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error while analyzing image.';

    return {
      detectedCategory: 'Unclear',
      severity: 'Low',
      autoGeneratedTranscript:
        'The uploaded image does not clearly show a relevant civic infrastructure issue or could not be processed reliably.',
      detectedObjects: [],
      confidenceScore: 0.12
    };
  }
}
